### ISSUE TITLE
Submission fails due to 'noCacheLookup' option

### ISSUE THREAD

**Issue by ezulkosk** [b-mueller/solfuzz#1]
Whenever I attempt to submit a contract for analysis, I receive the following error:

```
✔ Loaded solc v0.5.16 from local cache
✔ Compiled with solc v0.5.16 successfully
✖ Submitting data for analysis
Error: 403 You have no permission to use `noCacheLookup` option
```

The docs here: https://api.mythx.io/v1/openapi#operation/submitAnalysis, state

> [noCacheLookup] Optional. When true API won't look into the cache of past analyses, and always will run a new analysis for this request. The using of cache has no other side effects beside saving the runtime, thus this option is intended only for benchmarking, API health control, and debuging purposes. Itrequries NO_CACHE_LOOKUP permission to use, which is granted only to MythX team members.

I was able to circumvent the issue by deleting this line: https://github.com/b-mueller/solfuzz/blob/a62efa1b993d226463b17e6b6da2abf420d11d51/lib/client.js#L15 but not sure if a more "robust" fix is needed.

**Comment by b-mueller** [comment]
Hey @ezulkosk, that fix is perfectly fine actually. I'll merge this into the next release!

**Comment by b-mueller** [comment]
.. done 🙂
